language: ruby
rvm:
 - 2.3.1
 - 2.1.0
 - 2.0.0

script: "bundle exec rake spec"

branches:
  only:
      - master
      - /^issues\/.*$/

notifications:
  email:
    - robert.gurtler@anu.edu.au

env:
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.0.0"
