language: ruby
rvm:
 - 2.1.0

script: "bundle exec rake spec"

branches:
  only:
      - master
      - /^issues\/.*$/

notifications:
  email:
    - robert_gurtler@yahoo.com.au

env:
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
