sudo: false
language: ruby
rvm:
 - 2.3.4
 - 2.1.6

script: "bundle exec rake spec"

branches:
  only:
      - master
      - /^issues\/.*$/

notifications:
  email:
    - robert.gurtler@anu.edu.au

env:
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.0.0"
