language: ruby
sudo: false
cache: bundler

bundler_args: --without system_tests
before_install:
  - rm Gemfile.lock || true
  - gem update --system
script: "bundle exec rake spec"

matrix:
  fast_finish: true
  include:
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
    - rvm: 2.3.4
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
    - rvm: 2.4.4
      env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES=yes

notifications:
  email:
    - robert_gurtler@yahoo.com.au
  on_failures: always
