language: ruby
sudo: false
cache: bundler

rvm:
  - 2.4.1
  - 2.3.4
  - 2.1.6

bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake spec"

matrix:
  fast_finish: true
  include:
    - rvm: 2.3.4
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
    - rvm: 2.3.4
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
    - rvm: 2.4.1
      env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES=yes

notifications:
  email:
    - robert.gurtler@anu.edu.au
  on_failures: always
